# This is a TOML document.

area = "./asset/map/00.area"
camera_mode = 1 # camera::mode::center

[[elements]]
name     = "rin1"
pic      = "./asset/pic/rin.png"
width    = 245
height   = 224
rotate_t = 0 # animation::rotate_type::none
x        = 600
y        = 500

[[elements]]
pic      = "./asset/pic/rin.png"
width    = 245
height   = 224
rotate_t = 0 # animation::rotate_type::none
x        = 800
y        = 900

[[movables]]
name     = "yoshi"
pic      = "./asset/pic/yoshi.png"
width    = 64
height   = 64
rotate_t = 1    # animation::rotate_type::circle
x        = 10
y        = 10
flag_id  = 1    # element::flag::gravity
bind_cam = true # bind camera on this element
