# This is a TOML document.

area = "./asset/map/court.area"
# 1080 * 720 => mid point (540, 360)

[camera]
mode = 0 # camera::mode::top_left
x    = 60
y    = 60

# SDL table at https://wiki.libsdl.org/SDLKeycodeLookup

[[players]]
name     = "player1"
pic      = "./asset/pic/yoshi.png"
picwidth = 64
picheight= 64
rotate_t = 1    # animation::rotate_type::circle
x        = 800
y        = 400
flag_id  = 1    # element::flag::gravity
amplify  = 2.2
keyup    = 1073741906 # SDLK_UP
keydown  = 1073741905 # SDLK_DOWN
keyleft  = 1073741904 # SDLK_LEFT
keyright = 1073741903 # SDLK_RIGHT


[[players]]
name     = "player2"
pic      = "./asset/pic/yoshi.png"
picwidth = 64
picheight= 64
rotate_t = 1    # animation::rotate_type::circle
x        = 100
y        = 400
flag_id  = 1    # element::flag::gravity
amplify  = 2.2
keyup    = 119  # SDLK_w
keydown  = 115  # SDLK_s
keyleft  = 97   # SDLK_a
keyright = 100  # SDLK_d

[[obstacles]]
name     = "courtbar"
x        = 511
y        = 490
w        = 2
h        = 500
bounce_x = 2 # element::bounce_direction::same
bounce_y = 1 # element::bounce_direction::reverse

[[obstacles]]
name     = "courtbar_head"
x        = 511
y        = 460
w        = 2
h        = 30
bounce_x = 1 # element::bounce_direction::reverse
bounce_y = 2 # element::bounce_direction::same

# [[obstacles]]
# name     = "right_wall"
# x        = 512
# y        = 490
# w        = 3
# h        = 500
# bounce_x = 2 # element::bounce_direction::same
# bounce_y = 1 # element::bounce_direction::reverse
#
[[obstacles]]
name     = "left_wall"
x        = 165
y        = 0
w        = 5
h        = 720
bounce_x = 1 # element::bounce_direction::reverse
bounce_y = 2 # element::bounce_direction::same
#
# [[obstacles]]
# name     = "top_wall"
# x        = 512
# y        = 490
# w        = 3
# h        = 500
# bounce_x = 2 # element::bounce_direction::same
# bounce_y = 1 # element::bounce_direction::reverse
#
[[obstacles]]
name     = "floor"
x        = 0
y        = 630
w        = 1080
h        = 2
bounce_x = 2 # element::bounce_direction::same
bounce_y = 1 # element::bounce_direction::reverse

[[balls]]
name     = "ball"
x        = 200
y        = 200
pic      = "./asset/pic/ball.png"
picwidth = 91
picheight= 91
rotate_t = 0 # animation::rotate_type::none
flag_id  = 1 # element::flag::gravity & element::flag::map_only