# This is a TOML document.

area = "./asset/map/court.area"

[camera]
mode = 0 # camera::mode::top_left
x    = 60
y    = 60

[[elements]]
name     = "rin"
pic      = "./asset/pic/rin.png"
width    = 245
height   = 224
rotate_t = 0 # animation::rotate_type::none
x        = 600
y        = 500

[[elements]]
pic      = "./asset/pic/rin.png"
width    = 245
height   = 224
rotate_t = 0 # animation::rotate_type::none
x        = 200
y        = 200

[[movables]]
name     = "yoshi"
pic      = "./asset/pic/yoshi.png"
width    = 64
height   = 64
rotate_t = 1    # animation::rotate_type::circle
x        = 100
y        = 100
flag_id  = 1    # element::flag::gravity
